// <auto-generated />
using System;
using Data_Access.DataContext_Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220510154247_addingProductTable")]
    partial class addingProductTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Business_Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Business_Core.Entities.DynamicFormStructure", b =>
                {
                    b.Property<int>("DynamicFormStructureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DynamicFormStructureID"), 1L, 1);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NestSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("DynamicFormStructureID");

                    b.HasIndex("NestSubCategoryId")
                        .IsUnique();

                    b.ToTable("DynamicFormStructures");
                });

            modelBuilder.Entity("Business_Core.Entities.NestSubCategory", b =>
                {
                    b.Property<int>("NestSubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NestSubCategoryID"), 1L, 1);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("NestSubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("NestSubCategoryID");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("NestSubCategories");
                });

            modelBuilder.Entity("Business_Core.Entities.NestSubCategoryProductBrand", b =>
                {
                    b.Property<int>("NestSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.HasKey("NestSubCategoryId", "ProductBrandId");

                    b.HasIndex("ProductBrandId");

                    b.ToTable("NestSubCategoryProductBrands");
                });

            modelBuilder.Entity("Business_Core.Entities.Product.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("NestSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellUnits")
                        .HasColumnType("int");

                    b.Property<bool>("StockAvailiability")
                        .HasColumnType("bit");

                    b.HasKey("ProductID");

                    b.HasIndex("NestSubCategoryId");

                    b.HasIndex("ProductBrandId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Business_Core.Entities.Product.ProductBrand", b =>
                {
                    b.Property<int>("ProductBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductBrandID"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductBrandID");

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Business_Core.Entities.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Business_Core.Entities.DynamicFormStructure", b =>
                {
                    b.HasOne("Business_Core.Entities.NestSubCategory", "NestSubCategory")
                        .WithOne("DynamicFormStructure")
                        .HasForeignKey("Business_Core.Entities.DynamicFormStructure", "NestSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestSubCategory");
                });

            modelBuilder.Entity("Business_Core.Entities.NestSubCategory", b =>
                {
                    b.HasOne("Business_Core.Entities.SubCategory", "SubCategory")
                        .WithMany("NestSubCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Business_Core.Entities.NestSubCategoryProductBrand", b =>
                {
                    b.HasOne("Business_Core.Entities.NestSubCategory", "NestSubCategory")
                        .WithMany("NestSubCategoryProductBrand")
                        .HasForeignKey("NestSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business_Core.Entities.Product.ProductBrand", "ProductBrand")
                        .WithMany("NestSubCategoryProductBrand")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestSubCategory");

                    b.Navigation("ProductBrand");
                });

            modelBuilder.Entity("Business_Core.Entities.Product.Product", b =>
                {
                    b.HasOne("Business_Core.Entities.NestSubCategory", "NestSubCategory")
                        .WithMany()
                        .HasForeignKey("NestSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business_Core.Entities.Product.ProductBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestSubCategory");

                    b.Navigation("ProductBrand");
                });

            modelBuilder.Entity("Business_Core.Entities.SubCategory", b =>
                {
                    b.HasOne("Business_Core.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Business_Core.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Business_Core.Entities.NestSubCategory", b =>
                {
                    b.Navigation("DynamicFormStructure");

                    b.Navigation("NestSubCategoryProductBrand");
                });

            modelBuilder.Entity("Business_Core.Entities.Product.ProductBrand", b =>
                {
                    b.Navigation("NestSubCategoryProductBrand");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Business_Core.Entities.SubCategory", b =>
                {
                    b.Navigation("NestSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
